---
- name: create users
  hosts: g0
  gather_facts: no
  tasks:
    - name: display users
      debug: 
        msg:
          - "{{ item }}"
      loop: "{{ users|dict2items }}"
    - name: delete users
      user:
        name: "{{ item.key }}"
        group: "{{ item.value.group}}"
        state: present
      loop: "{{ users|dict2items }}"
      become: true
    - name: delete group
      group:
        name: "{{ item.value.group}}"
        state: present
      loop: "{{ users|dict2items }}"
      become: true
