---
- name: Use role 
  hosts: g1, g0
  
  roles:
    - geerlingguy.haproxy
  become: true

  tasks:
    - name: display vars
      debug:
        msg: "inventory var1 : {{ var1 }}\n inventory var2 : {{ var2 }}" 
