---
- name: create passwords
  hosts: g0
  tasks:
    - name: create passwords
      debug:
        msg:
          - "user : {{ item }} password : {{ lookup('password', 'credential/'+item+' length=9') }}"
      loop: "{{ query('lines', 'cat users.txt') }}"
      
    - name: create users
      user:
        name: "{{ item }}"
        password: "lookup('password', 'credential/'+item+ ' length=9') }}"
        state: "present"
      loop: "{{ query('lines', 'cat users.txt') }}"
      become: true
